### ISSUE TITLE
safari support?

### ISSUE THREAD

**Issue by chrisdrackett** [gavinsawyer/firebase-web-authn#1]
I believe that safari should support this on the current versions, but when I try creating a new login on both iOS and desktop safari I get a "Cancelled by user" error.

**Comment by gavinsawyer** [comment]
Hi Chris, are you referring to an error in the demo site or in your application?

To my knowledge this would only happen if the function isn't being called on a native click event. A library or framework you're using might be calling the function in a way that Safari can't associate with a user gesture.

Safari would also cancel WebAuthn if some part of the backend is set up incorrectly like serving the page without SSL or if your FirebaseWebAuthn API and your site don't have the same hostname.

This is how it looks in the demo which is using Angular and Angular Material:
```html
<button
  (click)="signInWithPasskey();"
  color="primary"
  mat-raised-button="">
  Sign in with passkey
</button>
```
```ts
this
  .signInWithPasskey = (): Promise<void> => signInWithPasskey(auth, functions)
  .then<void>((): void => matSnackBar.open("Sign-in successful.", "Okay") && void(0))
  .catch<never>((firebaseWebAuthnError: FirebaseWebAuthnError): never => matSnackBar.open(firebaseWebAuthnError.message, "Okay") && ((): never => {
    throw firebaseWebAuthnError;
  })());
```

**Comment by gavinsawyer** [comment]
I see that this issue is happening in the demo. Silly mistake in the internal config, fix incoming.

```ts
export const api: HttpsFunction = getFirebaseWebAuthnApi({
  authenticatorAttachment: process.env["USER_VERIFICATION_REQUIREMENT"] as AuthenticatorAttachment, // I'm surprised this worked on any browser
  relyingPartyName: process.env["RELYING_PARTY_NAME"] as string,
  userVerificationRequirement: process.env["USER_VERIFICATION_REQUIREMENT"] as UserVerificationRequirement,
});
```

**Comment by gavinsawyer** [comment]
It's working again in Safari. Thanks for opening this!

**Comment by chrisdrackett** [comment]
no worries! sorry for not supplying more info, I tried the demo first as my use-case requires safari support. I'll check out the code now ;)

**Comment by gavinsawyer** [comment]
My fault; I'm also using Safari so I didn't think there was an issue with the demo, I just haven't tested creating an account since I made it installable. It wouldn't have worked if you had installed it.
