### ISSUE TITLE
Bug: WebAuthn Error in Browser mallformed

### ISSUE THREAD

**Issue by czabaj** [gavinsawyer/firebase-web-authn#4]
I was trying to catch a specific error from the `browser` lib and I noticed 2 problems

1. the `FirebaseWebAuthnError` does not have a property `name` set to `FirebaseWebAuthnError` but just `Error`, I was thinking that subclasses of `Error` automatically reflect the name of the constructor/type, mislead by the MDN's
    > Subclasses like [TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) and [SyntaxError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError) provide their own name properties.
    > -- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name
    
    but unfortunately, it is not the case and it is not set automatically. The `FirebaseError` [sets the `name` explicitly as a `readonly` member property](https://github.com/firebase/firebase-js-sdk/blob/43e402fb49a081a59729290627c7b20099ca46a4/packages/util/src/errors.ts#L76). This is not a bug, but I'm writing my app in [ReScript](https://rescript-lang.org) and `instanceof` checks are little bit out of my reach so I was relied on the `name`,

1. the second problem is a bug IMHO, the `code` property contains double-prepended `firebaseWebAuthn/firebaseWebAuthn`, I believe there should be just one `firebaseWebAuthn/`, the private `firebaseWebAuthnErrorOptions` contains the correct form, so it is prepended in the options already and then prepended again [at this line](https://github.com/gavinsawyer/firebase-web-authn/blob/4fd29fa43400a3f02020129976c0bdbd3b15b0cd/libs/browser/src/lib/firebase-web-authn-error.ts#L28).
    
    <img width="444" alt="Screenshot 2023-08-08 at 17 52 30" src="https://github.com/gavinsawyer/firebase-web-authn/assets/47554112/025dae30-271d-430c-a275-dbecf33701f5">

This feels like a good first issue (for me) 😉

**Comment by gavinsawyer** [comment]
Thank you! I had no idea about the name property. Fix incoming on both
