### ISSUE TITLE
Browser: bump "firebase" to v10

### ISSUE THREAD

**Issue by czabaj** [gavinsawyer/firebase-web-authn#7]
The `@firebase-web-authn/browser` currently depends on `firebase@9` ~which is not tree-shakeable~, my app uses `firebase@10` which is modular and supports tree-shaking. The `@firebase-web-authn/browser` is, therefore, the only library, that depends on the older Firebase SDK and it loads the old SDK into my JavaScript bundle, which adds an extra ~600 KB 😳 

Can we upgrade the SDK to v10?

EDIT: It seems all the imports are already written in a non-namespaced way and therefore the SDK v9 is tree-shakeable as well, but still, it adds another version of SDK into my bundle. I just forced a single version of SDK in my bundle (via [Yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)) and everything seems to be working OK and the bundle is smaller by 200 KB, so the browser package should work with version 10. [Apparently the breaking-changes do not collide with the code in the browser package](https://firebase.google.com/support/release-notes/js), we just need a wider version range for the `firebase` dependency in the browser package `package.json`.

I would set the `firebase` as a `peerDependency` of the browser package, so it would never install its own version but always rely on the host project to provide the dependency in the selected version range. I think it is the right way to go, I just don't know how to set `peerDependency` for the browser library in Nx?

**Comment by gavinsawyer** [comment]
> Can we upgrade the SDK to v10?

I wrote the commit two days ago and have been waiting on the Firebase Angular SDK which tragically [isn't updated](https://github.com/angular/angularfire/pull/3402). I will hit push even though my build will fail just for you haha.

**Comment by gavinsawyer** [comment]
Got the new AngularFire and the demo is now working with a small hack:

```ts
this
      .signInWithPasskey = (): Promise<void> => signInWithPasskey(
        {
          ...this.auth, // This is missing the authStateReady async function, AngularFire v16 still in progress
          authStateReady: async (): Promise<void> => firstValueFrom<void>(new Observable<void>(
            (userObserver: Observer<void>): TeardownLogic => onAuthStateChanged(
              this.auth,
              (): void => userObserver.next(),
            ),
          )),
        },
        this.functions,
      )
      .then<void>(
        (): void => this.matSnackBar.open(
          "Sign-in successful.",
          "Okay",
        ) && void (0),
      )
      .catch<never>(
        (firebaseWebAuthnError: FirebaseWebAuthnError): never => this.matSnackBar.open(
          firebaseWebAuthnError.message || "Something went wrong.",
          "Okay",
        ) && ((): never => {
          throw firebaseWebAuthnError;
        })(),
      );
```
